"""phase_3_updates

Revision ID: 001_phase_3
Revises: 
Create Date: 2026-09-04 17:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001_phase_3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to conversations
    op.add_column('conversations', sa.Column('status', sa.String(), server_default='active', nullable=True))
    op.add_column('conversations', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    
    # Add new columns to messages
    op.add_column('messages', sa.Column('client_request_id', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('sequence', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_messages_client_request_id'), 'messages', ['client_request_id'], unique=False)
    op.create_index(op.f('ix_messages_sequence'), 'messages', ['sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_sequence'), table_name='messages')
    op.drop_index(op.f('ix_messages_client_request_id'), table_name='messages')
    op.drop_column('messages', 'sequence')
    op.drop_column('messages', 'client_request_id')
    
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_column('conversations', 'last_message_at')
    op.drop_column('conversations', 'status')
    # ### end Alembic commands ###
